---
- name: check whether certificates defined in vhosts exist
  ansible.builtin.stat: path={{ item.certificate_file }}
  register: apache__register_looped_stat_of_vhosts_ssl_certificate_files
  with_items: "{{ apache_vhosts_ssl }}"

- name: Generate configured Apache VirtualHost file and ensure correct owner/group/mode.
  ansible.builtin.template:
    src: "{{ apache_vhosts_template }}"
    dest: "{{ apache__server_conf_dir }}/{{ apache_vhosts_filename }}"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
  when: apache_create_vhosts | bool
