---
- name: Configure Apache's ports configuration.
  ansible.builtin.lineinfile:
    dest: "{{ apache_server_root }}/ports.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    mode: 0644
  with_items: "{{ apache_ports_configuration_items }}"
  notify: restart apache

- name: Enable configured Apache mods (Debian).
  ansible.builtin.file:
    src: "{{ apache_server_root }}/mods-available/{{ item }}.load"
    dest: "{{ apache_server_root }}/mods-enabled/{{ item }}.load"
    state: link
    mode: 0644
  with_items: "{{ apache_mods_enabled }}"
  notify: restart apache

- name: Disable configured Apache mods (Debian).
  ansible.builtin.file:
    path: "{{ apache_server_root }}/mods-enabled/{{ item }}.load"
    state: absent
  with_items: "{{ apache_mods_disabled }}"
  notify: restart apache

- name: check whether certificates defined in vhosts exist
  ansible.builtin.stat: "path={{ item.certificate_file }}"
  register: apache_ssl_certificates
  with_items: "{{ apache_vhosts_ssl }}"

- name: Generate configured Apache VirtualHost file in Debians 'site-available' directory and ensure correct owner/group/mode.
  ansible.builtin.template:
    src: "{{ apache_vhosts_template }}"
    dest: "{{ apache_conf_path }}/sites-available/{{ apache_vhosts_filename }}"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
  when: apache_create_vhosts | bool

- name: Add symlink to generated VirtualHost file in Debians 'sites-enabled' directory and ensure correct mode.
  ansible.builtin.file:
    src: "{{ apache_conf_path }}/sites-available/{{ apache_vhosts_filename }}"
    dest: "{{ apache_conf_path }}/sites-enabled/{{ apache_vhosts_filename }}"
    state: link
    mode: 0644
  notify: restart apache
  when: apache_create_vhosts | bool

- name: Remove default vhost from Debians 'sites-enabled' directory (when configured).
  ansible.builtin.file:
    path: "{{ apache_conf_path }}/sites-enabled/{{ apache_default_vhost_filename }}"
    state: absent
  notify: restart apache
  when: apache_remove_default_vhost
