---
- name: check whether certificates defined in vhosts exist
  ansible.builtin.stat: path={{ item.certificate_file }}
  register: apache__register_looped_stat_of_vhosts_ssl_certificate_files
  with_items: "{{ apache_vhosts_ssl }}"

- name: include tasks to safely generate vhost
  ansible.builtin.include_tasks: "_generate_vhost_standard.yml"
