---
- name: Update apt cache.
  ansible.builtin.apt: update_cache=yes cache_valid_time=3600

- name: Install Apache (Debian).
  ansible.builtin.apt:
    name: "{{ apache_packages }}"
    state: "{{ apache_packages_state }}"
