---
- name: Install Apache (Solaris).
  community.general.pkg5:
    name: "{{ apache_packages }}"
    state: "{{ apache_packages_state }}"
  register: apache__register_pk5__install

- name: set apache installed fact
  ansible.builtin.set_fact:
    apache__fact_install_changed: "{{ apache__register_pk5__install.changed }}"
