---
- name: Update Debians' APT cache.
  ansible.builtin.apt: update_cache=true cache_valid_time=86400

- name: Install Apache (Debian).
  ansible.builtin.apt:
    name: "{{ apache_packages }}"
    state: "{{ apache_packages_state }}"
  register: apache__register_apt__install

- name: set apache installed fact
  ansible.builtin.set_fact:
    apache__fact_install_changed: "{{ apache__register_apt__install.changed }}"
