---
- name: Converge
  hosts: all
  become: true

  vars:
    apache_vhosts:
      - servername: "example.com"
        documentroot: "/var/www/vhosts/example_com"

  roles:
    - role: "ansible-role-apache2"
