---
- name: Converge
  hosts: all
  become: true

  vars:
    apache_vhosts:
      - servername: "www.local1.dev"
        documentroot: "/var/www/vhosts/example_com"
      - servername: "wwww.local2.dev"
        loglevel: info
        errorlog: "${APACHE_LOG_DIR}/error.log"
        customlog:
          path: "${APACHE_LOG_DIR}/access.log"
          extra: "combined"
      - servername: "www.local3.dev"
        serveralias: "local3.dev"
        documentroot: "/var/www/html"
        extra_parameters: |
          # Redirect all requests to 'www' subdomain. Apache 2.4+
          RewriteEngine On
          RewriteCond %{HTTP_HOST} !^www\. [NC]
          RewriteRule ^(.*)$ %{REQUEST_SCHEME}://www.%{HTTP_HOST}%{REQUEST_URI} [R=302,L]

  roles:
    - role: "ansible-role-apache2"
