---
name: label size of PRs
permissions:
  pull-requests: write
"on":
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  size-label:
    runs-on: ubuntu-latest
    steps:
      - name: size-label
        uses: pascalgn/size-label-action@37a5ad4ae20ea8032abf169d953bcd661fd82cd3 # v0.5.0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
